### PR TITLE
Add functionality to generate TypeScript definitions

### PR DESCRIPTION
**Pull request by JamesSkemp**
> This replaces #151 

Based upon local testing (`npm install file:../..`), these changes appear to add proper TypeScript definitions to the library.

This change consists of the following:

1. Add TypeScript as a devDependency.
2. Add a new script to leverage TypeScript's built-in functionality to generate .d.ts files.
    - Note that I did try to have it generate one file, but couldn't get it to work, and looking at other projects they either are built with TypeScript, or are simpler. My hope is that adding some TS support will lead to someone with more knowledge than I improving the generation process. Or the library being rewritten in TypeScript. ;)
    - Git is marked to ignore the generated files in the types directory, which are built as part of the `prepublishOnly` script.

Based upon local testing, this then allows you to add the rpg-dice-roller package and import functionality (`import { DiceRoll } from 'rpg-dice-roller';`).

This relates to, and would close, #92 .

### CODE REVIEW

**Comment by GreenImp** [comment]
This is looking really good, but I'm getting errors running the `tsc -p declaration.tsconfig.json` script. Running it throws:

> src/parser/grammars/grammar.js:1:1 - error TS9005: Declaration emit for this file requires using private name 'peg$SyntaxError'. An explicit type annotation may unblock declaration emit.
>
> 1 import * as Dice from '../../Dice';
>  \~\~\~\~\~\~
>
> Found 1 error.

I can't really find much on that error, except this: https://stackoverflow.com/questions/60009092/declaration-will-not-emit-due-to-private-name-usage
Which, in that instance, seems to be a problem with using CommonJS exports, rather than ES module exports.

It could be due to how the `grammar.js` file is being generated; it's a bit hacky as PegJS (The Grammar parser) doesn't natively support exporting to ES modules. We're basically generating a file output to string, then wrapping it in an ES Module export - you can see the code in https://github.com/GreenImp/rpg-dice-roller/blob/develop/src/parser/grammars/generate.js
It's a bit convoluted.

I've just spent a while looking into options with PegJS, and the latest dev version does support exporting as ES modules: https://github.com/pegjs/pegjs/pull/481/files?file-filters%5B%5D=.js#diff-cd2c6b13fdcedf68a390c8bb6ea65cafR1293
But that's a dev version and I'm not sure how stable it is.

I also found a Typescript plugin for PegJS, which may or may not help: https://www.npmjs.com/package/ts-pegjs

**Comment by JamesSkemp** [comment]
Okay, was able to reproduce it. I've got three different local copies of the project, and never ran `build` on this fresh copy.

I was hoping I could exclude the generated file, but ran into https://github.com/microsoft/TypeScript/issues/33526#issuecomment-573330299 and switching the module type in tsconfig (since all we care about is the d.ts, not a final JS file) resulted in a variety of errors.

If src/parser/grammars/grammar.js doesn't exist then it builds without issue. Interestingly though, in VS Code I also get an "Unable to resolve path to module './grammars/grammar'." eslint error on the `import parser from './grammars/grammar';` line in src/parser/Parser.js, but TypeScript is fine ignoring it.

ts-pegjs appears to be a library to help use PegJS in TypeScript code.

The hacky way is to remove/rename that grammar.js file while the TS declarations are being created, and then put it back, or let the grammar process run after it ...

**Comment by GreenImp** [comment]
I think the generated `grammar.js` file should probably be included in the typescript definitions, to have full typescript coverage.

I've had a quick play around and I've got it working by manually modifying the generated `grammar.js` file to be a proper ES module (removing the IIFE). So at least we know that there's a fix. The problem is trying to get the grammar file generated in that format.
I might have to try and pull in that change to PegJS somehow. Maybe my own fork of it or something as it doesn't look like they're going to be released any time soon.

**Comment by GreenImp** [comment]
I've just raised #153 which should hopefully fix these issues by changing how the `grammar.js` file is rendered.
If you rebase your stuff off `develop` and give it another try. You'll just need to make sure you run `npm run build:grammars` before `npm run build:declaration`.

I'm thinking that it might actually be better to have the `build:declaration` script included at the end of the `prebuild` script, rather than `prepublishOnly`:

```json
"prebuild": "npm run build:grammars && npm run build:declaration",
```

`prebuild` is run when publishing, but also as part of the integration tests, so any issues would be caught there.

**Comment by JamesSkemp** [comment]
Nice. I haven't been able to find a way to get to the code that grammar.js defines in a test TypeScript project, but having that updated makes things easier. :)

Per your comment above, new script moved to `prebuild`. Generating the library locally and adding it as a local package gives TypeScript definitions as expected. 🎊

**Comment by GreenImp** [comment]
Looking good! I've just tested the build process and it seems to work nicely.

What's the issue you're having getting the `grammar.js` working in a Typescript project?

I've had a thought; the typescript definitions are being generated from the `src` files, which contain the original ES modules, and not the `lib/esm/bundle.js` file, which contains the actual files that will be brought in when using `import`.
Just wanted to check that this is correct?

**Comment by GreenImp** [comment]
Just reread your comment re grammar.js in Typescript and realised that you're probably meaning that you can't access the code from within your project.
That's probably correct actually, as the grammar file is only used internally (In the parser) and doesn't get exported anywhere publicly accessible.

**Comment by JamesSkemp** [comment]
Sorry, yup, that's what I was referring to. :)

The functionality that would be accessed is working as expected.

image

**Comment by GreenImp** [comment]
Awesome! So you're happy that this is all working okay? If so, I'll get it merged in :smile:

**Comment by JamesSkemp** [comment]
Yup, I think it's working great. :)

**Pull request merged**
