### PR TITLE
Replace heavy mathjs dependency with a lighter one

### PR DESCRIPTION
**Pull request by yunseok**
Removed MathJS to make the package lighter

### CODE REVIEW

**Comment by GreenImp** [comment]
I completely understand the need  for a smaller math parser - it is large.
However I'm also not overly keen on moving to something with a different syntax - With `expr-eval` it seems that you have to create a `Parser` object for each use, then evaluate it separaretly.

That's not to say I'm completely averse to it.
I'm wondering if it may be better to use the reduced version of MathJS (https://github.com/josdejong/mathjs-expression-parser), which would keep the syntax the same and only mean a change in the NPM include.
Also, looking at the package sizes, it looks like reduced MathJS (41kb) is smaller that expr-eval (68kb).

**Comment by yunseok** [comment]
> Does `expr-eval` provide any benefits over the reduced MathJS package?

I don't think so, I just wanted something similar to eval to remplace MathJS so the package is lighter. Though I think it's a good idea to add a reduced version of MathJS to make it lighter.

**Comment by GreenImp** [comment]
I've created another pull request (#87) which uses the reduced version of MathJS, to keep the syntax consistent.
Although it wasn't used, thank you for your contribution. It's really appreciated.

**Comment by GreenImp** [comment]
Just to let you know, I've released a patch version that uses the reduced size version of MathJS, which halves the package size: https://bundlephobia.com/result?p=rpg-dice-roller@3.1.4
There's still some bundle size changes I want to make, but it's difficult at the moment when I'm having to bundle UMD files for nodeJS. Once NodeJS fully supports ES imports then I can scrap those, which will reduce the filesize even more.

**Pull request closed without merging**
